program: tda_runner.py
method: grid
metric:
  name: Averaged test accuracy
  goal: maximize
project: ETTA-CLIP-Ablation
# Testing negative entropy threshold sensitivity
parameters:
  # Keep positive cache parameters fixed
  positive.shot_capacity:
    value: 3
  positive.alpha:
    value: 1.0
  positive.beta:
    value: 7.0

  # Keep other negative cache parameters fixed
  negative.shot_capacity:
    value: 2
  negative.alpha:
    value: 0.117
  negative.beta:
    value: 1.0
  
  # Test entropy threshold variations
  negative.entropy_threshold.lower:
    values: [0.1, 0.15, 0.2, 0.25, 0.3]  # Base value is 0.2
  negative.entropy_threshold.upper:
    values: [0.4, 0.45, 0.5, 0.55, 0.6]  # Base value is 0.5
  
  # Keep mask threshold fixed
  negative.mask_threshold.lower:
    value: 0.03
  negative.mask_threshold.upper:
    value: 1.0

command:
  - ${env}
  - python
  - ${program}
  - --config=configs/stanford_cars.yaml
  - --wandb-log
  - --datasets=stanford_cars
  - --backbone=RN50 