program: tda_runner.py
method: bayes
metric:
  name: Averaged test accuracy
  goal: maximize

parameters:
  positive.shot_capacity:
    distribution: int_uniform
    min: 1
    max: 32
  positive.alpha:
    distribution: uniform
    min: 0.5
    max: 5.0
  positive.beta:
    distribution: uniform
    min: 1.0
    max: 8.0
  negative.shot_capacity:
    distribution: int_uniform
    min: 1
    max: 32
  negative.alpha:
    distribution: uniform
    min: 0.1
    max: 1.0
  negative.beta:
    distribution: uniform
    min: 0.5
    max: 2.0
  negative.entropy_threshold.lower:
    distribution: uniform
    min: 0.1
    max: 0.3
  negative.entropy_threshold.upper:
    distribution: uniform
    min: 0.4
    max: 0.7

command:
  - ${env}
  - python
  - ${program}
  - --config=configs/imagenet.yaml
  - --wandb-log
  - --datasets=I
  - --backbone=RN50 