# Configuration for TDA Hyperparameters

# --- Positive Cache Configuration ---
positive:
  enabled: true
  shot_capacity: 32
  alpha: 0.8
  beta: 2.0

# --- Negative Cache Configuration ---
negative:
  enabled: true
  shot_capacity: 32
  alpha: 0.4
  beta: 1.0
  entropy_threshold:
    lower: 0.2
    upper: 0.7
  mask_threshold:
    lower: 0.2
    upper: 0.8